name: Hugo build check
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Actions-Hugo-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SYNC_CONTENT }}
          submodules: true       # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Build Hugo static files
        run: hugo -v --gc --minify
