name: Hugo build and deploy
on:
  push:
    branches: [ main ]
    paths:
      - 'assets/**'
      - 'content/**'
      - 'data/**'
      - 'static/**'
      - 'themes/**'
      - 'config.toml'
  workflow_run:
    workflows: ['Update theme']
    types:
      - completed
  workflow_dispatch:
jobs:
  Actions-Hugo-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SYNC_CONTENT }}
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Install
        run: npm install
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Build
        run: npm run build
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.GP_DEPLOY_KEY }}
          external_repository: kendrickcheung/kendrickcheung.github.io
          publish_branch: main
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ':rocket: ${{ github.event.head_commit.message }}'
          force_orphan: false  # once a year
      - name: Update Algolia index
        env:
          ALGOLIA_APP_ID: 2R1K9SKLQZ
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: 'blog'
          ALGOLIA_INDEX_FILE: './public/algolia.json'
        run: npm run algolia
      - name: Install coscmd
        run: sudo pip install coscmd
      - name: Configure coscmd
        env:
          COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
          COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
          COS_BUCKET_NAME: begi-1307578855
          COS_BUCKET_REGION: ap-guangzhou
        run: coscmd config -a $COS_SECRET_ID -s $COS_SECRET_KEY -b $COS_BUCKET_NAME -r $COS_BUCKET_REGION
      - name: Deploy to COS Bucket
        run: coscmd upload -r -s --delete -f public/ /
      - name: Refresh Qcloud CDN cache
        env:
          SECRET_ID: ${{ secrets.COS_SECRET_ID }}
          SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
        run: npm run qcloudcdn
